name: Build, Scan, and Push Docker Image

on:
  push:
    branches: [main]

env:
  PROJECT_ID: note-api-hs-heilbronn-devsecops-dream-team # TODO: update Google Cloud project id
  GAR_LOCATION: europe-west3 # TODO: update Artifact Registry location
  REPOSITORY: note-api # TODO: update Artifact Registry repository name

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Snyk Security Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --sarif-file-output=snyk.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/snyk.sarif 

  Build-and-Push-Docker-Image-To-GCR:
    runs-on: ubuntu-latest
    needs: security-scan
    permissions:
      id-token: write  # Required for authentication
      contents: read 
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/main:latest .
      
      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/main:latest 

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '${{ vars.WIF_PROVIDER }}'
          service_account: '${{ vars.WIF_SERVICE_ACCOUNT }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Docker
        run: |
          echo "Setting up Docker..."
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet
      
      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}:${{ github.sha }}"


      # - name: Push image to Artifact Registry
      #   run: |
      #     docker tag ghcr.io/${{ github.repository }}/main:latest \
      #       ${{ env.GAR_LOCATION }}-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/main:latest
      #     docker push ${{ env.GAR_LOCATION }}-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/main:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: '${{ env.PROJECT_ID }}'
          image: '${{ env.GAR_LOCATION }}-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}:${{ github.sha }}'
          region: ${{ env.GAR_LOCATION }}
          env_vars: BACKEND=memory
