name: Build, Scan, and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Snyk Security Scan
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --sarif-file-output=snyk.sarif
          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ github.workspace }}/snyk.sarif 

  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: security-scan
    permissions:
      id-token: write  # Required for authentication
      contents: read 
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/main:latest .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/main:latest
      
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
          service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'note-api'
      
      - name: Create Artifact Registry Repository
        id: create-repo
        run: |
          gcloud artifacts repositories describe cloud-run-source-deploy/note-api-hs-heilbronn-devsecops-dream-team --location=europe-west3 || \
          gcloud artifacts repositories create cloud-run-source-deploy/note-api-hs-heilbronn-devsecops-dream-team \
            --repository-format=docker \
            --location=europe-west3 \
            --description="Repository for note-api images"
      
      - name: Tag and Push Image to Artifact Registry
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/note-api/main:latest \
          europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/note-api-hs-heilbronn-devsecops-dream-team/note-api:latest
          docker push europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/cloud-run-source-deploy/note-api-hs-heilbronn-devsecops-dream-team/note-api:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'note-api-hs-heilbronn-devsecops-dream-team'
          image: 'europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api-hs-heilbronn-devsecops-dream-team/note-api:latest'
          region: 'europe-west3'
          env_vars: BACKEND=memory

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
          
  # Deploy-to-Google-Cloud-Run:
  #   runs-on: ubuntu-latest
  #   needs: Build-and-Push-Docker-Image
  #   permissions:
  #     id-token: write  # Required for authentication
  #     contents: read 
  #   steps:
  #     - name: Authenticate with Google Cloud
  #       id: auth
  #       uses: google-github-actions/auth@v1
  #       with:
  #         workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
  #         service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'

  #     - name: Set up Google Cloud SDK
  #       uses: google-github-actions/setup-gcloud@v1
  #       with:
  #         project_id: 'note-api'
      
  #     - name: Tag and Push Image to Artifact Registry
  #       run: |
  #         docker tag ghcr.io/${{ github.repository_owner }}/note-api/main:latest \
  #         europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api-hs-heilbronn-devsecops-dream-team/note-api:latest
  #         docker push europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api-hs-heilbronn-devsecops-dream-team/note-api:latest

  #     - name: Deploy to Cloud Run
  #       uses: google-github-actions/deploy-cloudrun@v1
  #       with:
  #         service: 'note-api-hs-heilbronn-devsecops-dream-team'
  #         image: 'europe-west3-docker.pkg.dev/hs-heilbronn-devsecops/note-api-hs-heilbronn-devsecops-dream-team/note-api:latest'
  #         region: 'europe-west3'
  #         env_vars: BACKEND=memory

  #     - name: 'Use output'
  #       run: 'curl "${{ steps.deploy.outputs.url }}"'