name: Build and Push Docker Image

on:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
          # username: ${{ vars.DOCKERHUB_USERNAME }}
          # password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     tags: ${{ vars.DOCKERHUB_USERNAME }}/clockbox:latest
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/main:latest .

      - name: Push the Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/main:latest

